/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsAnalogInData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsAnalogInData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsAnalogInData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsAnalogInData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsAnalogInData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ushort m_data {
    set {
      xsensdeviceapiPINVOKE.XsAnalogInData_m_data_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsAnalogInData_m_data_get(swigCPtr);
      return ret;
    } 
  }

  public XsAnalogInData() : this(xsensdeviceapiPINVOKE.new_XsAnalogInData__SWIG_0(), true) {
  }

  public XsAnalogInData(ushort data) : this(xsensdeviceapiPINVOKE.new_XsAnalogInData__SWIG_1(data), true) {
  }

}

}
