/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsAtomicInt : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsAtomicInt(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsAtomicInt obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsAtomicInt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsAtomicInt(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int m_value {
    set {
      xsensdeviceapiPINVOKE.XsAtomicInt_m_value_set(swigCPtr, value);
    } 
    get {
      int ret = xsensdeviceapiPINVOKE.XsAtomicInt_m_value_get(swigCPtr);
      return ret;
    } 
  }

  public XsAtomicInt(int val) : this(xsensdeviceapiPINVOKE.new_XsAtomicInt__SWIG_0(val), true) {
  }

  public XsAtomicInt() : this(xsensdeviceapiPINVOKE.new_XsAtomicInt__SWIG_1(), true) {
  }

  public void setValue(int val) {
    xsensdeviceapiPINVOKE.XsAtomicInt_setValue(swigCPtr, val);
  }

  public int value() {
    int ret = xsensdeviceapiPINVOKE.XsAtomicInt_value(swigCPtr);
    return ret;
  }

}

}
