/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsDevicePtrArray : XsDevicePtrArrayImpl {
  private HandleRef swigCPtr;

  internal XsDevicePtrArray(IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsDevicePtrArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsDevicePtrArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDevicePtrArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsDevicePtrArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsDevicePtrArray(uint sz, SWIGTYPE_p_p_XsDevice src) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_0(sz, SWIGTYPE_p_p_XsDevice.getCPtr(src)), true) {
  }

  public XsDevicePtrArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_1(sz), true) {
  }

  public XsDevicePtrArray() : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_2(), true) {
  }

  public XsDevicePtrArray(XsDevicePtrArray other) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_3(XsDevicePtrArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsDevicePtrArray(SWIGTYPE_p_p_XsDevice arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_4(SWIGTYPE_p_p_XsDevice.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsDevicePtrArray(SWIGTYPE_p_p_XsDevice arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsDevicePtrArray__SWIG_5(SWIGTYPE_p_p_XsDevice.getCPtr(arg0), sz), true) {
  }

}

}
