/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsDeviceIdArray : XsDeviceIdArrayImpl {
  private HandleRef swigCPtr;

  internal XsDeviceIdArray(IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsDeviceIdArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsDeviceIdArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDeviceIdArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsDeviceIdArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsDeviceIdArray(uint sz, XsDeviceId src) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_0(sz, XsDeviceId.getCPtr(src)), true) {
  }

  public XsDeviceIdArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_1(sz), true) {
  }

  public XsDeviceIdArray() : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_2(), true) {
  }

  public XsDeviceIdArray(XsDeviceIdArray other) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_3(XsDeviceIdArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsDeviceIdArray(XsDeviceId arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_4(XsDeviceId.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsDeviceIdArray(XsDeviceId arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsDeviceIdArray__SWIG_5(XsDeviceId.getCPtr(arg0), sz), true) {
  }

}

}
