/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsMutexLocker : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsMutexLocker(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsMutexLocker obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsMutexLocker() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsMutexLocker(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsMutexLocker(XsMutex m) : this(xsensdeviceapiPINVOKE.new_XsMutexLocker(XsMutex.getCPtr(m)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool _lock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutexLocker__lock(swigCPtr);
    return ret;
  }

  public bool unlock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutexLocker_unlock(swigCPtr);
    return ret;
  }

  public bool tryLock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutexLocker_tryLock(swigCPtr);
    return ret;
  }

}

}
