/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsMutex : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsMutex(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsMutex obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsMutex() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsMutex(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsMutex() : this(xsensdeviceapiPINVOKE.new_XsMutex(), true) {
  }

  public bool _lock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutex__lock(swigCPtr);
    return ret;
  }

  public bool tryLock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutex_tryLock(swigCPtr);
    return ret;
  }

  public bool unlock() {
    bool ret = xsensdeviceapiPINVOKE.XsMutex_unlock(swigCPtr);
    return ret;
  }

}

}
