/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsOutputConfiguration : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsOutputConfiguration(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsOutputConfiguration obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsOutputConfiguration() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsOutputConfiguration(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsDataIdentifier m_dataIdentifier {
    set {
      xsensdeviceapiPINVOKE.XsOutputConfiguration_m_dataIdentifier_set(swigCPtr, (int)value);
    } 
    get {
      XsDataIdentifier ret = (XsDataIdentifier)xsensdeviceapiPINVOKE.XsOutputConfiguration_m_dataIdentifier_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_frequency {
    set {
      xsensdeviceapiPINVOKE.XsOutputConfiguration_m_frequency_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsOutputConfiguration_m_frequency_get(swigCPtr);
      return ret;
    } 
  }

  public XsOutputConfiguration() : this(xsensdeviceapiPINVOKE.new_XsOutputConfiguration__SWIG_0(), true) {
  }

  public XsOutputConfiguration(XsDataIdentifier di, ushort freq) : this(xsensdeviceapiPINVOKE.new_XsOutputConfiguration__SWIG_1((int)di, freq), true) {
  }

}

}
