/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsPortInfoArray : XsPortInfoArrayImpl {
  private HandleRef swigCPtr;

  internal XsPortInfoArray(IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsPortInfoArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsPortInfoArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsPortInfoArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsPortInfoArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsPortInfoArray(uint sz, XsPortInfo src) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_0(sz, XsPortInfo.getCPtr(src)), true) {
  }

  public XsPortInfoArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_1(sz), true) {
  }

  public XsPortInfoArray() : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_2(), true) {
  }

  public XsPortInfoArray(XsPortInfoArray other) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_3(XsPortInfoArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsPortInfoArray(XsPortInfo arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_4(XsPortInfo.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsPortInfoArray(XsPortInfo arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsPortInfoArray__SWIG_5(XsPortInfo.getCPtr(arg0), sz), true) {
  }

}

}
