/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsRawGnssSatInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsRawGnssSatInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsRawGnssSatInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsRawGnssSatInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsRawGnssSatInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint m_itow {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_itow_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_itow_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_numSvs {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_numSvs_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_numSvs_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_res1 {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res1_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res1_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_res2 {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res2_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res2_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_res3 {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res3_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_res3_get(swigCPtr);
      return ret;
    } 
  }

  public XsSatInfo m_satInfos {
    set {
      xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_satInfos_set(swigCPtr, XsSatInfo.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsRawGnssSatInfo_m_satInfos_get(swigCPtr);
      XsSatInfo ret = (cPtr == IntPtr.Zero) ? null : new XsSatInfo(cPtr, false);
      return ret;
    } 
  }

  public XsRawGnssSatInfo() : this(xsensdeviceapiPINVOKE.new_XsRawGnssSatInfo(), true) {
  }

}

}
