/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsRawGpsSvInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsRawGpsSvInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsRawGpsSvInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsRawGpsSvInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsRawGpsSvInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint m_itow {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_itow_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_itow_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_nch {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_nch_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_nch_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_res1 {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_res1_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_res1_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_res2 {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_res2_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_res2_get(swigCPtr);
      return ret;
    } 
  }

  public XsSvInfo m_svInfos {
    set {
      xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_svInfos_set(swigCPtr, XsSvInfo.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsRawGpsSvInfo_m_svInfos_get(swigCPtr);
      XsSvInfo ret = (cPtr == IntPtr.Zero) ? null : new XsSvInfo(cPtr, false);
      return ret;
    } 
  }

  public XsRawGpsSvInfo() : this(xsensdeviceapiPINVOKE.new_XsRawGpsSvInfo(), true) {
  }

}

}
