/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsScrData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsScrData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsScrData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsScrData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsScrData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsUShortVector m_acc {
    set {
      xsensdeviceapiPINVOKE.XsScrData_m_acc_set(swigCPtr, XsUShortVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsScrData_m_acc_get(swigCPtr);
      XsUShortVector ret = (cPtr == IntPtr.Zero) ? null : new XsUShortVector(cPtr, false);
      return ret;
    } 
  }

  public XsUShortVector m_gyr {
    set {
      xsensdeviceapiPINVOKE.XsScrData_m_gyr_set(swigCPtr, XsUShortVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsScrData_m_gyr_get(swigCPtr);
      XsUShortVector ret = (cPtr == IntPtr.Zero) ? null : new XsUShortVector(cPtr, false);
      return ret;
    } 
  }

  public XsUShortVector m_mag {
    set {
      xsensdeviceapiPINVOKE.XsScrData_m_mag_set(swigCPtr, XsUShortVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsScrData_m_mag_get(swigCPtr);
      XsUShortVector ret = (cPtr == IntPtr.Zero) ? null : new XsUShortVector(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_short m_temp {
    set {
      xsensdeviceapiPINVOKE.XsScrData_m_temp_set(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(value));
    } 
    get {
      IntPtr cPtr = xsensdeviceapiPINVOKE.XsScrData_m_temp_get(swigCPtr);
      SWIGTYPE_p_unsigned_short ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
      return ret;
    } 
  }

  public XsScrData() : this(xsensdeviceapiPINVOKE.new_XsScrData(), true) {
  }

}

}
