/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsStringArray : XsStringArrayImpl {
  private HandleRef swigCPtr;

  internal XsStringArray(IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsStringArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsStringArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsStringArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsStringArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsStringArray(uint sz, XsString src) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_0(sz, XsString.getCPtr(src)), true) {
  }

  public XsStringArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_1(sz), true) {
  }

  public XsStringArray() : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_2(), true) {
  }

  public XsStringArray(XsStringArray other) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_3(XsStringArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsStringArray(XsString arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_4(XsString.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsStringArray(XsString arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsStringArray__SWIG_5(XsString.getCPtr(arg0), sz), true) {
  }

  public XsString join(XsString separator) {
    XsString ret = new XsString(xsensdeviceapiPINVOKE.XsStringArray_join(swigCPtr, XsString.getCPtr(separator)), true);
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void fromSplicedString(XsString src, XsString separators) {
    xsensdeviceapiPINVOKE.XsStringArray_fromSplicedString(swigCPtr, XsString.getCPtr(src), XsString.getCPtr(separators));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
