/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsSyncSettingArray : XsSyncSettingArrayImpl {
  private HandleRef swigCPtr;

  internal XsSyncSettingArray(IntPtr cPtr, bool cMemoryOwn) : base(xsensdeviceapiPINVOKE.XsSyncSettingArray_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsSyncSettingArray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSyncSettingArray() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsSyncSettingArray(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public XsSyncSettingArray(uint sz, XsSyncSetting src) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_0(sz, XsSyncSetting.getCPtr(src)), true) {
  }

  public XsSyncSettingArray(uint sz) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_1(sz), true) {
  }

  public XsSyncSettingArray() : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_2(), true) {
  }

  public XsSyncSettingArray(XsSyncSettingArray other) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_3(XsSyncSettingArray.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsSyncSettingArray(XsSyncSetting arg0, uint sz, XsDataFlags flags) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_4(XsSyncSetting.getCPtr(arg0), sz, (int)flags), true) {
  }

  public XsSyncSettingArray(XsSyncSetting arg0, uint sz) : this(xsensdeviceapiPINVOKE.new_XsSyncSettingArray__SWIG_5(XsSyncSetting.getCPtr(arg0), sz), true) {
  }

}

}
