/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

public enum XsSyncFunction {
  XSF_StartRecording,
  XSF_StopRecording,
  XSF_ResetTimer,
  XSF_TriggerIndication,
  XSF_IntervalTransitionMeasurement,
  XSF_IntervalTransitionRecording,
  XSF_GotoOperational,
  XSF_SampleAndSend,
  XSF_SendLatest,
  XSF_ClockBiasEstimation,
  XSF_PulseWithModulation,
  XSF_StartSampling,
  XSF_Invalid,
  XSF_Count = XSF_Invalid
}

}
