/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsUsbHubInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsUsbHubInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsUsbHubInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsUsbHubInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsUsbHubInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsUsbHubInfo(int hubid) : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_0(hubid), true) {
  }

  public XsUsbHubInfo() : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_1(), true) {
  }

  public XsUsbHubInfo(XsUsbHubInfo other) : this(xsensdeviceapiPINVOKE.new_XsUsbHubInfo__SWIG_2(XsUsbHubInfo.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool parentPathMatches(XsUsbHubInfo other) {
    bool ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_parentPathMatches(swigCPtr, XsUsbHubInfo.getCPtr(other));
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isValid() {
    bool ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_isValid(swigCPtr);
    return ret;
  }

  public int hub() {
    int ret = xsensdeviceapiPINVOKE.XsUsbHubInfo_hub(swigCPtr);
    return ret;
  }

}

}
