/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsUShortVector : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsUShortVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsUShortVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsUShortVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsUShortVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public XsUShortVector() : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_0(), true) {
  }

  public XsUShortVector(ushort v1, ushort v2, ushort v3) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_1(v1, v2, v3), true) {
  }

  public XsUShortVector(SWIGTYPE_p_unsigned_short a) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_2(SWIGTYPE_p_unsigned_short.getCPtr(a)), true) {
  }

  public XsUShortVector(XsUShortVector other) : this(xsensdeviceapiPINVOKE.new_XsUShortVector__SWIG_3(XsUShortVector.getCPtr(other)), true) {
    if (xsensdeviceapiPINVOKE.SWIGPendingException.Pending) throw xsensdeviceapiPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = xsensdeviceapiPINVOKE.XsUShortVector_size(swigCPtr);
    return ret;
  }

  public ushort at(int index) {
    ushort ret = xsensdeviceapiPINVOKE.XsUShortVector_at(swigCPtr, index);
    return ret;
  }

}

}
