/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XDA {

using System;
using System.Runtime.InteropServices;

public class XsUtcTime : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsUtcTime(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(XsUtcTime obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsUtcTime() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xsensdeviceapiPINVOKE.delete_XsUtcTime(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint m_nano {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_nano_set(swigCPtr, value);
    } 
    get {
      uint ret = xsensdeviceapiPINVOKE.XsUtcTime_m_nano_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_year {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_year_set(swigCPtr, value);
    } 
    get {
      ushort ret = xsensdeviceapiPINVOKE.XsUtcTime_m_year_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_month {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_month_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_month_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_day {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_day_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_day_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_hour {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_hour_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_hour_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_minute {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_minute_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_minute_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_second {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_second_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_second_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_valid {
    set {
      xsensdeviceapiPINVOKE.XsUtcTime_m_valid_set(swigCPtr, value);
    } 
    get {
      byte ret = xsensdeviceapiPINVOKE.XsUtcTime_m_valid_get(swigCPtr);
      return ret;
    } 
  }

  public static XsUtcTime currentTime() {
    XsUtcTime ret = new XsUtcTime(xsensdeviceapiPINVOKE.XsUtcTime_currentTime(), true);
    return ret;
  }

  public XsUtcTime() : this(xsensdeviceapiPINVOKE.new_XsUtcTime(), true) {
  }

}

}
